# -*- coding: utf-8 -*-
"""UberAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hXlkUErKanmuIhiyM8sHZq7xs1dymn0L
"""

from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("UberAnalyticsProject") \
    .getOrCreate()

df =spark.read.parquet('/content/travel.parquet')

df.show(5)

df.printSchema()

"""#Data Cleaning"""

from pyspark.sql.functions import col
clean_df=df.filter(col("trip_distance")>0)
clean_df=clean_df.filter(col("fare_amount")>0)
clean_df=clean_df.filter(col("passenger_count")>0)
df.show(5)

"""Feature Engineering"""

#Trip Duration
from pyspark.sql.functions import unix_timestamp
clean_df=clean_df.withColumn(
    "trip_duration_minutes",
    (unix_timestamp(col("tpep_dropoff_datetime"))-unix_timestamp(col("tpep_pickup_datetime")))/60
)

#Extract Hour of Ride
from pyspark.sql.functions import hour
clean_df=clean_df.withColumn("pickup_hour",hour(col("tpep_pickup_datetime")))

"""# Analytics 1

"""

# Busiest Hours
from pyspark.sql.functions import count
busy_hours=clean_df.groupBy("pickup_hour").agg(count("*").alias("ride_count")) \
.orderBy("ride_count",ascending=False)
busy_hours.show()

#Top Pickup Locations
from pyspark.sql.functions import count
pickup_locations=clean_df.groupBy("PULocationID").agg(count("*").alias("trip_count")) \
.orderBy("trip_count",ascending=False)
pickup_locations.show()

#Daily Revenue
from pyspark.sql.functions import sum,to_date
revenue_df=clean_df.withColumn(
    "date",
    to_date(col("tpep_pickup_datetime"))
)

daily_revenue=revenue_df.groupBy("date").agg(sum("fare_amount").alias("total_revenue"))
daily_revenue.show()

#Average Trip Distance
from pyspark.sql.functions import avg
avg_distance=clean_df.agg(avg("trip_distance").alias("average_distance"))
avg_distance.show()

busy_hours.write.mode("overwrite").parquet("/content/busy_hours")
pickup_locations.write.mode("overwrite").parquet("/content/pickup_locations")
daily_revenue.write.mode("overwrite").parquet("/content/daily_revenue")

"""#SQL Version"""

clean_df.createOrReplaceTempView("trips")

spark.sql("""
Select pickup_hour,count(*) as trip_count
from trips
group by pickup_hour
order by trip_count desc
""").show()

"""#Performance Optimization"""

clean_df.repartition("pickup_hour")

clean_df.cache()